### ISSUE TITLE
knn density estimate produces overflow error for high-dimensional data

### ISSUE THREAD

**Issue by mike-powell** [CoAxLab/DeBaCl#41]
I have had success using the DeBaCl kNN density estimate for low-dimensional data.  I get an overflow error with significantly higher dimension data (500k+ length vectors), which I presume is attributed to the $v_d$ (unit ball volume) in the denominator of the density estimate formula.  An equation I found for the unit ball volume suggests this would be nearly 0, leading to a divide by nearly 0 and an overflow error.  I'm using 1/(distance to the kth neighbor) as a density estimate placeholder for now.

**Comment by papayawarrior** [comment]
Pull request #54 is my best effort to address this by adding errors and/or warnings when underflows or overflows occur, as well as more explanation in the API docs about why those numerical problems can occur.

Ultimately, this the density estimate is where the curse of dimensionality bites hardest, so there isn't a good software fix. For level set tree estimation, the simplest workaround is to call the `knn_density` function with the dimension `p` set to 1, because the LST procedure only really needs the order of the points with respect to their density values, not the values themselves. Using 1/radius is also a good option, although that can still underflow.

**Comment by papayawarrior** [comment]
Pull request #54 is merged, so closing.
